name: accountmanager
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  equatable: ^2.0.0
  excel: ^2.0.0-null-safety-3
  firebase: ^9.0.1
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.2
  hooks_riverpod: ^0.14.0+3
  intl: ^0.17.0
  js: ^0.6.3
  logger: ^1.0.0
  provider: ^5.0.0
  rive: ^0.7.9
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  simple_animations: ^3.1.1
  # state_notifier: ^0.7.0
  super_tooltip: ^1.0.1
  supercharged: ^2.0.0
  universal_html: ^2.0.8
  universal_io: ^2.0.4
  # universal_html: 1.2.4

dev_dependencies:
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.8.1
  mockito: ^5.0.7
  random_string: ^2.2.0-nullsafety
  # test: ^1.16.5

dependency_overrides:
  # archive : ^2.0.0
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/docx/template.docx
    - assets/images/
    - assets/icon/
    - assets/rive/
    - assets/svg/
    - assets/avatars/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
        - asset: assets/fonts/AllertaStencil-Regular.ttf
    - family: Allerta
      fonts:
        - asset: assets/fonts/AllertaStencil-Regular.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # fonts:
  #   - family:  MyFlutterApp
  #     fonts:
  #      - asset: assets/fonts/MyFlutterApp.ttf